Tiger.LetExp {
  decs =
  [Tiger.VarDec {name = ("a", 0); escape = ref (true); typ = None;
     init = (Tiger.IntExp 0);
     pos =
     { Tiger.pos_fname = ""; pos_lnum = 3; pos_bol = 30; pos_cnum = 31 }};
    (Tiger.FunctionDec
       [{ Tiger.name = ("g", 2);
          params =
          [{ Tiger.field_name = ("a", 0); escape = ref (true);
             typ = ("int", 1);
             field_pos =
             { Tiger.pos_fname = ""; pos_lnum = 5; pos_bol = 41;
               pos_cnum = 53 }
             }
            ];
          result =
          (Some (("int", 1),
                 { Tiger.pos_fname = ""; pos_lnum = 5; pos_bol = 41;
                   pos_cnum = 59 }));
          body =
          (Tiger.VarExp
             (Tiger.SimpleVar (("a", 0),
                { Tiger.pos_fname = ""; pos_lnum = 5; pos_bol = 41;
                  pos_cnum = 66 }
                )));
          pos =
          { Tiger.pos_fname = ""; pos_lnum = 5; pos_bol = 41; pos_cnum = 51 }
          }
         ])
    ];
  body =
  (Tiger.SeqExp
     [(Tiger.CallExp {func = ("g", 2);
         args =
         [((Tiger.IntExp 2),
           { Tiger.pos_fname = ""; pos_lnum = 7; pos_bol = 72; pos_cnum = 75
             })
           ];
         pos =
         { Tiger.pos_fname = ""; pos_lnum = 7; pos_bol = 72; pos_cnum = 73 }},
       { Tiger.pos_fname = ""; pos_lnum = 7; pos_bol = 72; pos_cnum = 73 })]);
  pos = { Tiger.pos_fname = ""; pos_lnum = 2; pos_bol = 26; pos_cnum = 26 }}
