Tiger.IfExp {
  test =
  (Tiger.SeqExp
     [(Tiger.OpExp {left = (Tiger.IntExp 5); oper = Tiger.GtOp;
         right = (Tiger.IntExp 4);
         pos =
         { Tiger.pos_fname = ""; pos_lnum = 3; pos_bol = 43; pos_cnum = 47 }},
       { Tiger.pos_fname = ""; pos_lnum = 3; pos_bol = 43; pos_cnum = 47 })]);
  then' = (Tiger.IntExp 13);
  else' =
  (Some (Tiger.StringExp (" ",
           { Tiger.pos_fname = ""; pos_lnum = 3; pos_bol = 43; pos_cnum = 68
             }
           )));
  pos = { Tiger.pos_fname = ""; pos_lnum = 3; pos_bol = 43; pos_cnum = 43 }}
