Tiger.LetExp {
  decs =
  [(Tiger.TypeDec
      [{ Tiger.tydec_name = ("rectype", 4);
         ty =
         (Tiger.RecordTy
            [{ Tiger.field_name = ("name", 1); escape = ref (true);
               typ = ("string", 0);
               field_pos =
               { Tiger.pos_fname = ""; pos_lnum = 4; pos_bol = 45;
                 pos_cnum = 62 }
               };
              { Tiger.field_name = ("id", 3); escape = ref (true);
                typ = ("int", 2);
                field_pos =
                { Tiger.pos_fname = ""; pos_lnum = 4; pos_bol = 45;
                  pos_cnum = 76 }
                }
              ]);
         tydec_pos =
         { Tiger.pos_fname = ""; pos_lnum = 4; pos_bol = 45; pos_cnum = 51 }
         }
        ]);
    Tiger.VarDec {name = ("rec1", 5); escape = ref (true); typ = None;
      init =
      Tiger.RecordExp {
        fields =
        [(("name", 1),
          (Tiger.StringExp ("Name",
             { Tiger.pos_fname = ""; pos_lnum = 5; pos_bol = 84;
               pos_cnum = 116 }
             )),
          { Tiger.pos_fname = ""; pos_lnum = 5; pos_bol = 84; pos_cnum = 106
            });
          (("id", 3), (Tiger.IntExp 0),
           { Tiger.pos_fname = ""; pos_lnum = 5; pos_bol = 84; pos_cnum = 119
             })
          ];
        typ = ("rectype", 4);
        pos =
        { Tiger.pos_fname = ""; pos_lnum = 5; pos_bol = 84; pos_cnum = 97 }};
      pos =
      { Tiger.pos_fname = ""; pos_lnum = 5; pos_bol = 84; pos_cnum = 85 }}
    ];
  body =
  (Tiger.SeqExp
     [(Tiger.AssignExp {
         var =
         (Tiger.FieldVar (
            (Tiger.SimpleVar (("rec1", 5),
               { Tiger.pos_fname = ""; pos_lnum = 7; pos_bol = 128;
                 pos_cnum = 129 }
               )),
            ("nam", 6),
            { Tiger.pos_fname = ""; pos_lnum = 7; pos_bol = 128;
              pos_cnum = 129 }
            ));
         exp =
         (Tiger.StringExp ("asd",
            { Tiger.pos_fname = ""; pos_lnum = 7; pos_bol = 128;
              pos_cnum = 145 }
            ));
         pos =
         { Tiger.pos_fname = ""; pos_lnum = 7; pos_bol = 128; pos_cnum = 129
           }},
       { Tiger.pos_fname = ""; pos_lnum = 7; pos_bol = 128; pos_cnum = 129 })
       ]);
  pos = { Tiger.pos_fname = ""; pos_lnum = 3; pos_bol = 40; pos_cnum = 40 }}
