Tiger.LetExp {
  decs =
  [Tiger.VarDec {name = "a"; typ = None; init = (Tiger.IntExp 0);
     pos =
     { Tiger.pos_fname = ""; pos_lnum = 3; pos_bol = 143; pos_cnum = 144 }};
    Tiger.VarDec {name = "a"; typ = None;
      init =
      (Tiger.StringExp (" ",
         { Tiger.pos_fname = ""; pos_lnum = 4; pos_bol = 155; pos_cnum = 167
           }
         ));
      pos =
      { Tiger.pos_fname = ""; pos_lnum = 4; pos_bol = 155; pos_cnum = 156 }}
    ];
  body =
  (Tiger.SeqExp
     [((Tiger.IntExp 0),
       { Tiger.pos_fname = ""; pos_lnum = 6; pos_bol = 172; pos_cnum = 173 })
       ]);
  pos = { Tiger.pos_fname = ""; pos_lnum = 2; pos_bol = 139; pos_cnum = 139 }}
