Tiger.LetExp {
  decs =
  [(Tiger.TypeDec
      [{ Tiger.tydec_name = "arrayty";
         ty =
         (Tiger.ArrayTy ("int",
            { Tiger.pos_fname = ""; pos_lnum = 4; pos_bol = 58; pos_cnum = 83
              }
            ));
         tydec_pos =
         { Tiger.pos_fname = ""; pos_lnum = 4; pos_bol = 58; pos_cnum = 64 }
         }
        ]);
    Tiger.VarDec {name = "a"; escape = ref (true); typ = None;
      init =
      Tiger.ArrayExp {typ = "arrayty"; size = (Tiger.IntExp 10);
        init =
        (Tiger.StringExp (" ",
           { Tiger.pos_fname = ""; pos_lnum = 6; pos_bol = 88; pos_cnum = 116
             }
           ));
        pos =
        { Tiger.pos_fname = ""; pos_lnum = 6; pos_bol = 88; pos_cnum = 98 }};
      pos =
      { Tiger.pos_fname = ""; pos_lnum = 6; pos_bol = 88; pos_cnum = 89 }}
    ];
  body =
  (Tiger.SeqExp
     [((Tiger.IntExp 0),
       { Tiger.pos_fname = ""; pos_lnum = 8; pos_bol = 121; pos_cnum = 122 })
       ]);
  pos = { Tiger.pos_fname = ""; pos_lnum = 3; pos_bol = 54; pos_cnum = 54 }}
