Tiger.ForExp {var = ("i", 0); escape = ref (true); lo = (Tiger.IntExp 10);
  hi =
  (Tiger.StringExp (" ",
     { Tiger.pos_fname = ""; pos_lnum = 2; pos_bol = 77; pos_cnum = 92 }));
  body =
  Tiger.AssignExp {
    var =
    (Tiger.SimpleVar (("i", 0),
       { Tiger.pos_fname = ""; pos_lnum = 3; pos_bol = 97; pos_cnum = 98 }));
    exp =
    Tiger.OpExp {
      left =
      (Tiger.VarExp
         (Tiger.SimpleVar (("i", 0),
            { Tiger.pos_fname = ""; pos_lnum = 3; pos_bol = 97;
              pos_cnum = 103 }
            )));
      oper = Tiger.MinusOp; right = (Tiger.IntExp 1);
      pos =
      { Tiger.pos_fname = ""; pos_lnum = 3; pos_bol = 97; pos_cnum = 103 }};
    pos = { Tiger.pos_fname = ""; pos_lnum = 3; pos_bol = 97; pos_cnum = 98 }};
  pos = { Tiger.pos_fname = ""; pos_lnum = 2; pos_bol = 77; pos_cnum = 77 }}
