Tiger.LetExp {decs = [];
  body =
  (Tiger.SeqExp
     [(Tiger.AssignExp {
         var =
         (Tiger.SubscriptVar (
            (Tiger.SimpleVar (("arr1", 0),
               { Tiger.pos_fname = ""; pos_lnum = 6; pos_bol = 36;
                 pos_cnum = 36 }
               )),
            (Tiger.IntExp 0),
            { Tiger.pos_fname = ""; pos_lnum = 6; pos_bol = 36; pos_cnum = 36
              }
            ));
         exp = (Tiger.IntExp 1);
         pos =
         { Tiger.pos_fname = ""; pos_lnum = 6; pos_bol = 36; pos_cnum = 36 }},
       { Tiger.pos_fname = ""; pos_lnum = 6; pos_bol = 36; pos_cnum = 36 });
       (Tiger.AssignExp {
          var =
          (Tiger.FieldVar (
             (Tiger.SubscriptVar (
                (Tiger.SimpleVar (("arr2", 1),
                   { Tiger.pos_fname = ""; pos_lnum = 7; pos_bol = 50;
                     pos_cnum = 50 }
                   )),
                (Tiger.IntExp 3),
                { Tiger.pos_fname = ""; pos_lnum = 7; pos_bol = 50;
                  pos_cnum = 50 }
                )),
             ("name", 2),
             { Tiger.pos_fname = ""; pos_lnum = 7; pos_bol = 50;
               pos_cnum = 50 }
             ));
          exp =
          (Tiger.StringExp ("kati",
             { Tiger.pos_fname = ""; pos_lnum = 7; pos_bol = 50;
               pos_cnum = 71 }
             ));
          pos =
          { Tiger.pos_fname = ""; pos_lnum = 7; pos_bol = 50; pos_cnum = 50 }},
        { Tiger.pos_fname = ""; pos_lnum = 7; pos_bol = 50; pos_cnum = 50 });
       (Tiger.AssignExp {
          var =
          (Tiger.SubscriptVar (
             (Tiger.SimpleVar (("arr3", 3),
                { Tiger.pos_fname = ""; pos_lnum = 8; pos_bol = 74;
                  pos_cnum = 74 }
                )),
             (Tiger.IntExp 34),
             { Tiger.pos_fname = ""; pos_lnum = 8; pos_bol = 74;
               pos_cnum = 74 }
             ));
          exp =
          (Tiger.StringExp ("sfd",
             { Tiger.pos_fname = ""; pos_lnum = 8; pos_bol = 74;
               pos_cnum = 90 }
             ));
          pos =
          { Tiger.pos_fname = ""; pos_lnum = 8; pos_bol = 74; pos_cnum = 74 }},
        { Tiger.pos_fname = ""; pos_lnum = 8; pos_bol = 74; pos_cnum = 74 });
       (Tiger.AssignExp {
          var =
          (Tiger.SubscriptVar (
             (Tiger.FieldVar (
                (Tiger.SimpleVar (("rec2", 4),
                   { Tiger.pos_fname = ""; pos_lnum = 10; pos_bol = 94;
                     pos_cnum = 94 }
                   )),
                ("dates", 5),
                { Tiger.pos_fname = ""; pos_lnum = 10; pos_bol = 94;
                  pos_cnum = 94 }
                )),
             (Tiger.IntExp 0),
             { Tiger.pos_fname = ""; pos_lnum = 10; pos_bol = 94;
               pos_cnum = 94 }
             ));
          exp = (Tiger.IntExp 2323);
          pos =
          { Tiger.pos_fname = ""; pos_lnum = 10; pos_bol = 94; pos_cnum = 94
            }},
        { Tiger.pos_fname = ""; pos_lnum = 10; pos_bol = 94; pos_cnum = 94 })
       ]);
  pos = { Tiger.pos_fname = ""; pos_lnum = 2; pos_bol = 27; pos_cnum = 27 }}
