Tiger.LetExp {
  decs =
  [(Tiger.TypeDec
      [{ Tiger.tydec_name = "rectype";
         ty =
         (Tiger.RecordTy
            [{ Tiger.field_name = "name"; escape = ref (true);
               typ = "string";
               field_pos =
               { Tiger.pos_fname = ""; pos_lnum = 4; pos_bol = 52;
                 pos_cnum = 69 }
               };
              { Tiger.field_name = "id"; escape = ref (true); typ = "int";
                field_pos =
                { Tiger.pos_fname = ""; pos_lnum = 4; pos_bol = 52;
                  pos_cnum = 82 }
                }
              ]);
         tydec_pos =
         { Tiger.pos_fname = ""; pos_lnum = 4; pos_bol = 52; pos_cnum = 58 }
         }
        ]);
    Tiger.VarDec {name = "b"; escape = ref (true);
      typ =
      (Some ("rectype",
             { Tiger.pos_fname = ""; pos_lnum = 5; pos_bol = 90;
               pos_cnum = 97 }));
      init =
      (Tiger.VarExp
         (Tiger.SimpleVar ("nil",
            { Tiger.pos_fname = ""; pos_lnum = 5; pos_bol = 90;
              pos_cnum = 108 }
            )));
      pos =
      { Tiger.pos_fname = ""; pos_lnum = 5; pos_bol = 90; pos_cnum = 91 }}
    ];
  body =
  (Tiger.SeqExp
     [(Tiger.AssignExp {
         var =
         (Tiger.SimpleVar ("b",
            { Tiger.pos_fname = ""; pos_lnum = 9; pos_bol = 117;
              pos_cnum = 118 }
            ));
         exp =
         (Tiger.VarExp
            (Tiger.SimpleVar ("nil",
               { Tiger.pos_fname = ""; pos_lnum = 9; pos_bol = 117;
                 pos_cnum = 123 }
               )));
         pos =
         { Tiger.pos_fname = ""; pos_lnum = 9; pos_bol = 117; pos_cnum = 118
           }},
       { Tiger.pos_fname = ""; pos_lnum = 9; pos_bol = 117; pos_cnum = 118 })
       ]);
  pos = { Tiger.pos_fname = ""; pos_lnum = 2; pos_bol = 46; pos_cnum = 46 }}
