Tiger.LetExp {
  decs =
  [(Tiger.TypeDec
      [{ Tiger.tydec_name = "rectype";
         ty =
         (Tiger.RecordTy
            [{ Tiger.field_name = "name"; typ = "string";
               field_pos =
               { Tiger.pos_fname = ""; pos_lnum = 3; pos_bol = 78;
                 pos_cnum = 95 }
               };
              { Tiger.field_name = "id"; typ = "int";
                field_pos =
                { Tiger.pos_fname = ""; pos_lnum = 3; pos_bol = 78;
                  pos_cnum = 108 }
                }
              ]);
         tydec_pos =
         { Tiger.pos_fname = ""; pos_lnum = 3; pos_bol = 78; pos_cnum = 84 }
         }
        ]);
    Tiger.VarDec {name = "a"; typ = None;
      init =
      (Tiger.VarExp
         (Tiger.SimpleVar ("nil",
            { Tiger.pos_fname = ""; pos_lnum = 5; pos_bol = 117;
              pos_cnum = 126 }
            )));
      pos =
      { Tiger.pos_fname = ""; pos_lnum = 5; pos_bol = 117; pos_cnum = 118 }}
    ];
  body =
  (Tiger.SeqExp
     [((Tiger.VarExp
          (Tiger.SimpleVar ("a",
             { Tiger.pos_fname = ""; pos_lnum = 7; pos_bol = 133;
               pos_cnum = 134 }
             ))),
       { Tiger.pos_fname = ""; pos_lnum = 7; pos_bol = 133; pos_cnum = 134 })
       ]);
  pos = { Tiger.pos_fname = ""; pos_lnum = 2; pos_bol = 73; pos_cnum = 73 }}
