Tiger.LetExp {
  decs =
  [(Tiger.FunctionDec
      [{ Tiger.name = "g";
         params =
         [{ Tiger.field_name = "a"; typ = "int";
            field_pos =
            { Tiger.pos_fname = ""; pos_lnum = 3; pos_bol = 49; pos_cnum = 62
              }
            };
           { Tiger.field_name = "b"; typ = "string";
             field_pos =
             { Tiger.pos_fname = ""; pos_lnum = 3; pos_bol = 49;
               pos_cnum = 70 }
             }
           ];
         result =
         (Some ("int",
                { Tiger.pos_fname = ""; pos_lnum = 3; pos_bol = 49;
                  pos_cnum = 79 }));
         body =
         (Tiger.VarExp
            (Tiger.SimpleVar ("a",
               { Tiger.pos_fname = ""; pos_lnum = 3; pos_bol = 49;
                 pos_cnum = 86 }
               )));
         pos =
         { Tiger.pos_fname = ""; pos_lnum = 3; pos_bol = 49; pos_cnum = 59 }
         }
        ])
    ];
  body =
  (Tiger.SeqExp
     [(Tiger.CallExp {func = "g";
         args =
         [((Tiger.IntExp 3),
           { Tiger.pos_fname = ""; pos_lnum = 5; pos_bol = 91; pos_cnum = 94
             });
           ((Tiger.StringExp ("one",
               { Tiger.pos_fname = ""; pos_lnum = 5; pos_bol = 91;
                 pos_cnum = 100 }
               )),
            { Tiger.pos_fname = ""; pos_lnum = 5; pos_bol = 91;
              pos_cnum = 100 });
           ((Tiger.IntExp 5),
            { Tiger.pos_fname = ""; pos_lnum = 5; pos_bol = 91;
              pos_cnum = 102 })
           ];
         pos =
         { Tiger.pos_fname = ""; pos_lnum = 5; pos_bol = 91; pos_cnum = 92 }},
       { Tiger.pos_fname = ""; pos_lnum = 5; pos_bol = 91; pos_cnum = 92 })]);
  pos = { Tiger.pos_fname = ""; pos_lnum = 2; pos_bol = 45; pos_cnum = 45 }}
