Tiger.LetExp {
  decs =
  [Tiger.VarDec {name = ("d", 0); escape = ref (true); typ = None;
     init = (Tiger.IntExp 0);
     pos =
     { Tiger.pos_fname = ""; pos_lnum = 3; pos_bol = 39; pos_cnum = 40 }}
    ];
  body =
  (Tiger.SeqExp
     [((Tiger.VarExp
          (Tiger.FieldVar (
             (Tiger.SimpleVar (("d", 0),
                { Tiger.pos_fname = ""; pos_lnum = 5; pos_bol = 52;
                  pos_cnum = 53 }
                )),
             ("f", 1),
             { Tiger.pos_fname = ""; pos_lnum = 5; pos_bol = 52;
               pos_cnum = 53 }
             ))),
       { Tiger.pos_fname = ""; pos_lnum = 5; pos_bol = 52; pos_cnum = 53 })]);
  pos = { Tiger.pos_fname = ""; pos_lnum = 2; pos_bol = 34; pos_cnum = 34 }}
