Tiger.LetExp {
  decs =
  [(Tiger.TypeDec
      [{ Tiger.tydec_name = ("intlist", 2);
         ty =
         (Tiger.RecordTy
            [{ Tiger.field_name = ("hd", 1); escape = ref (true);
               typ = ("int", 0);
               field_pos =
               { Tiger.pos_fname = ""; pos_lnum = 4; pos_bol = 61;
                 pos_cnum = 79 }
               };
              { Tiger.field_name = ("tl", 3); escape = ref (true);
                typ = ("intlist", 2);
                field_pos =
                { Tiger.pos_fname = ""; pos_lnum = 4; pos_bol = 61;
                  pos_cnum = 88 }
                }
              ]);
         tydec_pos =
         { Tiger.pos_fname = ""; pos_lnum = 4; pos_bol = 61; pos_cnum = 68 }
         }
        ]);
    (Tiger.TypeDec
       [{ Tiger.tydec_name = ("tree", 7);
          ty =
          (Tiger.RecordTy
             [{ Tiger.field_name = ("key", 4); escape = ref (true);
                typ = ("int", 0);
                field_pos =
                { Tiger.pos_fname = ""; pos_lnum = 7; pos_bol = 124;
                  pos_cnum = 138 }
                };
               { Tiger.field_name = ("children", 6); escape = ref (true);
                 typ = ("treelist", 5);
                 field_pos =
                 { Tiger.pos_fname = ""; pos_lnum = 7; pos_bol = 124;
                   pos_cnum = 148 }
                 }
               ]);
          tydec_pos =
          { Tiger.pos_fname = ""; pos_lnum = 7; pos_bol = 124; pos_cnum = 131
            }
          }
         ]);
    (Tiger.TypeDec
       [{ Tiger.tydec_name = ("treelist", 5);
          ty =
          (Tiger.RecordTy
             [{ Tiger.field_name = ("hd", 1); escape = ref (true);
                typ = ("tree", 7);
                field_pos =
                { Tiger.pos_fname = ""; pos_lnum = 8; pos_bol = 168;
                  pos_cnum = 187 }
                };
               { Tiger.field_name = ("tl", 3); escape = ref (true);
                 typ = ("treelist", 5);
                 field_pos =
                 { Tiger.pos_fname = ""; pos_lnum = 8; pos_bol = 168;
                   pos_cnum = 197 }
                 }
               ]);
          tydec_pos =
          { Tiger.pos_fname = ""; pos_lnum = 8; pos_bol = 168; pos_cnum = 175
            }
          }
         ]);
    Tiger.VarDec {name = ("lis", 9); escape = ref (true);
      typ =
      (Some (("intlist", 2),
             { Tiger.pos_fname = ""; pos_lnum = 10; pos_bol = 212;
               pos_cnum = 222 }));
      init =
      Tiger.RecordExp {
        fields =
        [(("hd", 1), (Tiger.IntExp 0),
          { Tiger.pos_fname = ""; pos_lnum = 10; pos_bol = 212;
            pos_cnum = 243 });
          (("tl", 3),
           (Tiger.VarExp
              (Tiger.SimpleVar (("nil", 8),
                 { Tiger.pos_fname = ""; pos_lnum = 10; pos_bol = 212;
                   pos_cnum = 253 }
                 ))),
           { Tiger.pos_fname = ""; pos_lnum = 10; pos_bol = 212;
             pos_cnum = 249 })
          ];
        typ = ("intlist", 2);
        pos =
        { Tiger.pos_fname = ""; pos_lnum = 10; pos_bol = 212; pos_cnum = 233
          }};
      pos =
      { Tiger.pos_fname = ""; pos_lnum = 10; pos_bol = 212; pos_cnum = 214 }}
    ];
  body =
  (Tiger.SeqExp
     [((Tiger.VarExp
          (Tiger.SimpleVar (("lis", 9),
             { Tiger.pos_fname = ""; pos_lnum = 13; pos_bol = 265;
               pos_cnum = 269 }
             ))),
       { Tiger.pos_fname = ""; pos_lnum = 13; pos_bol = 265; pos_cnum = 269 })
       ]);
  pos = { Tiger.pos_fname = ""; pos_lnum = 2; pos_bol = 35; pos_cnum = 35 }}
