Tiger.LetExp {
  decs =
  [(Tiger.FunctionDec
      [{ Tiger.name = "try";
         params =
         [{ Tiger.field_name = "c"; escape = ref (true); typ = "int";
            field_pos =
            { Tiger.pos_fname = ""; pos_lnum = 2; pos_bol = 4; pos_cnum = 19
              }
            }
           ];
         result = None;
         body =
         (Tiger.SeqExp
            [(Tiger.ForExp {var = "r"; escape = ref (true);
                lo = (Tiger.IntExp 0); hi = (Tiger.IntExp 10);
                body =
                Tiger.IfExp {
                  test =
                  Tiger.IfExp {
                    test =
                    Tiger.IfExp {
                      test =
                      Tiger.OpExp {left = (Tiger.IntExp 1);
                        oper = Tiger.GtOp; right = (Tiger.IntExp 0);
                        pos =
                        { Tiger.pos_fname = ""; pos_lnum = 5; pos_bol = 53;
                          pos_cnum = 60 }};
                      then' =
                      Tiger.OpExp {left = (Tiger.IntExp 1);
                        oper = Tiger.GtOp; right = (Tiger.IntExp 2);
                        pos =
                        { Tiger.pos_fname = ""; pos_lnum = 5; pos_bol = 53;
                          pos_cnum = 68 }};
                      else' = (Some (Tiger.IntExp 0));
                      pos =
                      { Tiger.pos_fname = ""; pos_lnum = 5; pos_bol = 53;
                        pos_cnum = 60 }};
                    then' =
                    Tiger.OpExp {left = (Tiger.IntExp 1); oper = Tiger.GtOp;
                      right = (Tiger.IntExp 3);
                      pos =
                      { Tiger.pos_fname = ""; pos_lnum = 5; pos_bol = 53;
                        pos_cnum = 76 }};
                    else' = (Some (Tiger.IntExp 0));
                    pos =
                    { Tiger.pos_fname = ""; pos_lnum = 5; pos_bol = 53;
                      pos_cnum = 60 }};
                  then' =
                  (Tiger.VarExp
                     (Tiger.SimpleVar ("c",
                        { Tiger.pos_fname = ""; pos_lnum = 6; pos_bol = 82;
                          pos_cnum = 93 }
                        )));
                  else' = None;
                  pos =
                  { Tiger.pos_fname = ""; pos_lnum = 5; pos_bol = 53;
                    pos_cnum = 57 }};
                pos =
                { Tiger.pos_fname = ""; pos_lnum = 4; pos_bol = 30;
                  pos_cnum = 33 }},
              { Tiger.pos_fname = ""; pos_lnum = 4; pos_bol = 30;
                pos_cnum = 33 })
              ]);
         pos =
         { Tiger.pos_fname = ""; pos_lnum = 2; pos_bol = 4; pos_cnum = 15 } }
        ])
    ];
  body =
  (Tiger.SeqExp
     [(Tiger.CallExp {func = "try";
         args =
         [((Tiger.IntExp 0),
           { Tiger.pos_fname = ""; pos_lnum = 8; pos_bol = 97; pos_cnum = 104
             })
           ];
         pos =
         { Tiger.pos_fname = ""; pos_lnum = 8; pos_bol = 97; pos_cnum = 100 }},
       { Tiger.pos_fname = ""; pos_lnum = 8; pos_bol = 97; pos_cnum = 100 })]);
  pos = { Tiger.pos_fname = ""; pos_lnum = 1; pos_bol = 0; pos_cnum = 0 }}
