Tiger.LetExp {
  decs =
  [(Tiger.FunctionDec
      [{ Tiger.name = "g";
         params =
         [{ Tiger.field_name = "a"; typ = "int";
            field_pos =
            { Tiger.pos_fname = ""; pos_lnum = 3; pos_bol = 48; pos_cnum = 61
              }
            };
           { Tiger.field_name = "b"; typ = "string";
             field_pos =
             { Tiger.pos_fname = ""; pos_lnum = 3; pos_bol = 48;
               pos_cnum = 69 }
             }
           ];
         result =
         (Some ("int",
                { Tiger.pos_fname = ""; pos_lnum = 3; pos_bol = 48;
                  pos_cnum = 78 }));
         body =
         (Tiger.VarExp
            (Tiger.SimpleVar ("a",
               { Tiger.pos_fname = ""; pos_lnum = 3; pos_bol = 48;
                 pos_cnum = 85 }
               )));
         pos =
         { Tiger.pos_fname = ""; pos_lnum = 3; pos_bol = 48; pos_cnum = 58 }
         }
        ])
    ];
  body =
  (Tiger.SeqExp
     [(Tiger.CallExp {func = "g";
         args =
         [((Tiger.StringExp ("one",
              { Tiger.pos_fname = ""; pos_lnum = 5; pos_bol = 90;
                pos_cnum = 97 }
              )),
           { Tiger.pos_fname = ""; pos_lnum = 5; pos_bol = 90; pos_cnum = 97
             })
           ];
         pos =
         { Tiger.pos_fname = ""; pos_lnum = 5; pos_bol = 90; pos_cnum = 91 }},
       { Tiger.pos_fname = ""; pos_lnum = 5; pos_bol = 90; pos_cnum = 91 })]);
  pos = { Tiger.pos_fname = ""; pos_lnum = 2; pos_bol = 44; pos_cnum = 44 }}
