Tiger.LetExp {
  decs =
  [(Tiger.FunctionDec
      [{ Tiger.name = "g";
         params =
         [{ Tiger.field_name = "a"; escape = ref (true); typ = "int";
            field_pos =
            { Tiger.pos_fname = ""; pos_lnum = 3; pos_bol = 164;
              pos_cnum = 176 }
            }
           ];
         result =
         (Some ("int",
                { Tiger.pos_fname = ""; pos_lnum = 3; pos_bol = 164;
                  pos_cnum = 182 }));
         body =
         (Tiger.VarExp
            (Tiger.SimpleVar ("a",
               { Tiger.pos_fname = ""; pos_lnum = 3; pos_bol = 164;
                 pos_cnum = 189 }
               )));
         pos =
         { Tiger.pos_fname = ""; pos_lnum = 3; pos_bol = 164; pos_cnum = 174
           }
         }
        ]);
    (Tiger.FunctionDec
       [{ Tiger.name = "g";
          params =
          [{ Tiger.field_name = "a"; escape = ref (true); typ = "int";
             field_pos =
             { Tiger.pos_fname = ""; pos_lnum = 4; pos_bol = 191;
               pos_cnum = 203 }
             }
            ];
          result =
          (Some ("int",
                 { Tiger.pos_fname = ""; pos_lnum = 4; pos_bol = 191;
                   pos_cnum = 209 }));
          body =
          (Tiger.VarExp
             (Tiger.SimpleVar ("a",
                { Tiger.pos_fname = ""; pos_lnum = 4; pos_bol = 191;
                  pos_cnum = 216 }
                )));
          pos =
          { Tiger.pos_fname = ""; pos_lnum = 4; pos_bol = 191; pos_cnum = 201
            }
          }
         ])
    ];
  body =
  (Tiger.SeqExp
     [((Tiger.IntExp 0),
       { Tiger.pos_fname = ""; pos_lnum = 6; pos_bol = 221; pos_cnum = 222 })
       ]);
  pos = { Tiger.pos_fname = ""; pos_lnum = 2; pos_bol = 160; pos_cnum = 160 }}
