Tiger.LetExp {
  decs =
  [(Tiger.FunctionDec
      [{ Tiger.name = ("g", 4);
         params =
         [{ Tiger.field_name = ("a", 1); escape = ref (true);
            typ = ("int", 0);
            field_pos =
            { Tiger.pos_fname = ""; pos_lnum = 3; pos_bol = 48; pos_cnum = 61
              }
            };
           { Tiger.field_name = ("b", 3); escape = ref (true);
             typ = ("string", 2);
             field_pos =
             { Tiger.pos_fname = ""; pos_lnum = 3; pos_bol = 48;
               pos_cnum = 69 }
             }
           ];
         result =
         (Some (("int", 0),
                { Tiger.pos_fname = ""; pos_lnum = 3; pos_bol = 48;
                  pos_cnum = 78 }));
         body =
         (Tiger.VarExp
            (Tiger.SimpleVar (("a", 1),
               { Tiger.pos_fname = ""; pos_lnum = 3; pos_bol = 48;
                 pos_cnum = 85 }
               )));
         pos =
         { Tiger.pos_fname = ""; pos_lnum = 3; pos_bol = 48; pos_cnum = 58 }
         }
        ])
    ];
  body =
  (Tiger.SeqExp
     [(Tiger.CallExp {func = ("g", 4);
         args =
         [((Tiger.StringExp ("one",
              { Tiger.pos_fname = ""; pos_lnum = 5; pos_bol = 90;
                pos_cnum = 97 }
              )),
           { Tiger.pos_fname = ""; pos_lnum = 5; pos_bol = 90; pos_cnum = 97
             })
           ];
         pos =
         { Tiger.pos_fname = ""; pos_lnum = 5; pos_bol = 90; pos_cnum = 91 }},
       { Tiger.pos_fname = ""; pos_lnum = 5; pos_bol = 90; pos_cnum = 91 })]);
  pos = { Tiger.pos_fname = ""; pos_lnum = 2; pos_bol = 44; pos_cnum = 44 }}
